/* Generated by wayland-scanner 1.14.0 */

/*
 * Copyright © 2017 Markus Ongyerth
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

extern const struct wl_interface wl_output_interface;
extern const struct wl_interface wl_surface_interface;
extern const struct wl_interface z_background_surface_interface;

static const struct wl_interface *types[] = {
	&z_background_surface_interface,
	&wl_surface_interface,
	&wl_output_interface,
};

static const struct wl_message z_background_requests[] = {
	{ "destroy", "", types + 0 },
	{ "get_background_surface", "no", types + 0 },
};

static const struct wl_message z_background_events[] = {
	{ "create_background", "", types + 0 },
};

WL_EXPORT const struct wl_interface z_background_interface = {
	"z_background", 1,
	2, z_background_requests,
	1, z_background_events,
};

static const struct wl_message z_background_surface_events[] = {
	{ "remove", "", types + 0 },
	{ "set_output", "o", types + 2 },
};

WL_EXPORT const struct wl_interface z_background_surface_interface = {
	"z_background_surface", 1,
	0, NULL,
	2, z_background_surface_events,
};

